---

- name: Put galaxy.ini file in place
  template: src=galaxy.ini.j2
            dest={{ galaxy_path }}/config/galaxy.ini
  become_user: galaxy

# Conf.xml files
- name: Upload job_conf.xml file
  copy: src=job_conf.xml 
        dest={{ galaxy_path }}/config/job_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload shed_tool_conf.xml if it doesnt exist already so we dont wipe out tools
  copy: src=shed_tool_conf.xml force=no
        dest={{ galaxy_path }}/config/shed_tool_conf.xml
        owner=galaxy
        group=galaxy
- name: Make sure shed_tool has correct location to tools 
  lineinfile: dest={{ galaxy_path }}/config/shed_tool_conf.xml regexp='^\<toolbox'
              line='<toolbox tool_path="shed_tools">'
- name: Upload tool_sheds_conf.xml if it doesnt exist
  copy: src=tool_sheds_conf.xml force=no
        dest={{ galaxy_path }}/config/tool_sheds_conf.xml
        owner=galaxy
        group=galaxy
