---
# Gluster Fileserver tasks
- name: Create galaxy user
  user: name=galaxy uid=1001

- name: Install fileserver packages
  apt: pkg={{ item }} state=installed
  with_items: fileserver_packages

- name: Create gluster volume
  gluster_volume:
    state: present
    transport: tcp 
    name: "{{ galaxy_gluster_vol }}"
    brick: "{{ item }}"
    cluster: '{{ play_hosts }}'
  run_once: true
  with_items: fileserver_data_paths
   
- name: Start gluster volume
  gluster_volume: state=started name=galaxy

- name: Create subdirs in gluster volume
  file: name={{ item }} state=directory owner=galaxy 
  with_items: galaxy_paths
