---
# NFS Fileserver tasks

# done here since not common task
- name: Update apt cache
  apt: update-cache=yes
  ignore_errors: yes # source and i386 packages not on mirror
- name: Upgrade packages
  apt: upgrade=dist

- name: Install fileserver packages
  apt: pkg={{item}} state=installed
  with_flattened: 
    - ${fileserver_packages}

- name: Create mount dir for galaxy data
  file: path=/var/nfs/galaxydata state=directory

- name: Add data to NFS exports template
  lineinfile: dest=/etc/exports state=present regexp="/var/nfs/galaxydata" line="/var/nfs/galaxydata    *(rw,sync,no_root_squash,subtree_check,no_wdelay)"
  notify: restart nfs

