---
# NFS Fileserver tasks
- name: Create galaxy user
  user: name=galaxy uid=1001

- name: Install fileserver packages
  apt: pkg={{ item }} state=installed
  with_items: fileserver_packages

- name: Create nfs dirs for galaxy
  file: path={{ item }} 
        state=directory
        owner=galaxy
        group=galaxy
  with_items:
  - "{{ data_nfs_share }}"
  - "{{ tool_nfs_share }}"
  - "{{ galaxy_nfs_share }}"

- name: Add data to NFS exports template
  lineinfile: dest=/etc/exports state=present
              regexp="{{ item }}"
              line="{{ item }}    *(rw,sync,no_root_squash,subtree_check,no_wdelay)"
  with_items:
  - "{{ data_nfs_share }}"
  - "{{ tool_nfs_share }}"
  - "{{ galaxy_nfs_share }}"
  notify: restart nfs

