---
# NFS Fileserver tasks

- name: Install fileserver packages
  apt: pkg={{item}} state=installed
  with_flattened: 
    - ${fileserver_packages}

- name: Create mount dir for galaxy data
  file: path={{ fileserver_nfs_share }} state=directory

- name: Add data to NFS exports template
  lineinfile: dest=/etc/exports state=present
              regexp="{{ fileserver_nfs_share }}"
              line="{{ fileserver_nfs_share }}    *(rw,sync,no_root_squash,subtree_check,no_wdelay)"
  notify: restart nfs

