---
# Role installs mirrors 

# prepare packages
- name: Install packages for mirror
  apt: pkg={{ item }} state=installed
  with_items: mirror_packages
- name: Install virtualenv
  pip: name=virtualenv state=present

# Put nginx conf script in place
- name: Adding nginx mirror configuration file
  copy: src=nginx_mirror.conf dest=/opt/nginx/conf/nginx.conf
- name: Restart nginx
  service: name=nginx state=restarted

# Apt mirror
- name: Creating apt mirror directory
  file: path=/mnt/mirrors/ubuntumirror mode=755 owner=root group=admin state=directory
- name: Setting keyring directory for apt mirror
  file: path=/home/mirrorkeyring state=directory
- name: Importing keyring for apt mirror
  command: gpg --no-default-keyring --keyring /home/mirrorkeyring/trustedkeys.gpg --import /usr/share/keyrings/ubuntu-archive-keyring.gpg
- name: Build apt mirror
  script: mirrorbuild.sh

# PyPI mirror
- name: Install pypi mirror downloader bandersnatch
  pip: name=bandersnatch state=present virtualenv=/home/admin/virtenvs/pypi_mirror
- name: Creating pypi mirror path
  file: path=/mnt/mirrors/pypimirror state=directory
- name: Installing bandersnatch.conf
  copy: src=bandersnatch.conf dest=/etc/bandersnatch.conf  
- name: Build PyPI mirror
  script: pypimirror_builder.sh

