---

core_packages:
  - nfs-common

data_share: "{{ fileserver_ip }}:{{ data_nfs_share }}"
tool_share: "{{ fileserver_ip }}:{{ tool_nfs_share }}"
galaxy_share: "{{ fileserver_ip }}:{{ galaxy_nfs_share }}"

mount_shares:
  - "{{ data_share }}"
  - "{{ tool_share }}"
  - "{{ galaxy_share }}"

mount_paths:
  - "{{ data_path }}"
  - "{{ tool_path }}"
  - "{{ galaxy_path }}"


