---
# Gluster Fileserver tasks
- name: Create galaxy user
  user: name=galaxy uid={{ galaxy_uid }} gid={{ galaxy_gid }}
  
- name: Fix etc/hosts for gluster
  lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item][hostvars[item]['private_ip_port']]['ipv4']['address'] }}'
                line="{{ hostvars[item][hostvars[item]['private_ip_port']]['ipv4']['address'] }}\t{{ item }}"
  with_items: 
  - "{{ groups['fileserver'] }}"

- name: Install fileserver packages
  apt: pkg={{ item }} state=installed
  with_items: fileserver_packages

- name: Create gluster volume
  gluster_volume:
    state: present
    transport: tcp 
    name: "{{ galaxy_gluster_vol }}"
    brick: "{{ item }}"
    cluster: '{{ play_hosts }}'
  run_once: true
  with_items: fileserver_glusterbrick_paths 
   
- name: Set gluster volume options
  gluster_volume:
    cluster: '{{ play_hosts }}'
    state: present
    brick: "{{ item }}"
    name: "{{ galaxy_gluster_vol }}"
    options: {performance.io-thread-count: "40", performance.cache-size: "1GB"}
  run_once: true
  with_items: fileserver_glusterbrick_paths 

- name: Start gluster volume
  gluster_volume: state=started name=galaxy

- name: Create subdir in gluster volume
  file: name={{ item }} state=directory owner=galaxy 
  with_items:
  - data
