---
# Rebooting and waiting until done

- name: Reboot system
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for system to come back
  local_action: wait_for host={{ ansible_ssh_host }}
                port={{ ansible_ssh_port }}
                state=started
                delay=2
  sudo: false
