---
# Rebooting and waiting until done

- name: Reboot system
  command: /sbin/reboot

- name: waiting for system to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
                delay=2 # seconds
                port=22
  sudo: false
