---
# Vars for master installation
postgres_version: 9.1
postgres_home: /usr/lib/postgresql/{{ postgres_version }}/bin
proftpd_pkg: proftpd-1.3.4a
proftpd_install_dir: /opt/proftpd

master_packages:
  - nfs-kernel-server
  - postgresql
  - mercurial
  # Required for compiling ProFTPd (must match installed PostgreSQL version!)
  - libpq-dev
  - postgresql-server-dev-9.1
  # not sure about these galaxy pkgs, are they only needed for tools maybe?
  - gfortran
  - default-jdk
  - python-rpy
  - xvfb

slurm_drmaa_url: http://apps.man.poznan.pl/trac/slurm-drmaa/downloads/9
slurm_drmaa_pkg: slurm-drmaa-1.0.7
