---

postgres_version: 9.3
postgres_packages:
  - postgresql
  - postgresql-contrib

proftpd_pkg: proftpd-1.3.4a
proftpd_install_dir: /opt/proftpd
proftpd_packages:
  - postgresql-server-dev-{{ postgres_version }}
  - libpq-dev 
  - libssl-dev
  - stow
