---

# Shutdown all services that connect galaxy cluster
# - galaxy
# - slurm
# - postgres
# - proftpd
# - unmount nfs
#
# Nginx is left on since it is used for package mirror

- name: Shutdown services
  service: name={{ item }} state=stopped
  with_items:
  - galaxy
  - slurm-llnl
  - proftpd
  - postgresql

- name: Unmount shared galaxy-dist, ftp, tool filesystems
  mount: src={{ item.0 }} name={{ item.1 }} fstype=nfs state=unmounted opts=defaults,_netdev
  with_together:
  - nfs_mount_shares
  - nfs_mount_paths

- name: Unmount data volume
  mount: src={{ data_share }} name={{ data_path }} fstype=glusterfs state=unmounted opts=defaults,_netdev
