---

- name: Install percolator dependencies
  apt: pkg={{ item }} state=installed
  with_items: "{{ percolator_deps }}"

- name: Patch xsds stream-extraction.hxx. Ugly.
  lineinfile: dest=/usr/include/xsd/cxx/tree/stream-extraction.hxx regexp='^(.*) push_back(.*)$' line="{{ item }}" backrefs=yes 
  with_items:
    - '\1 this->push_back\2' 
    - '\1  this->push_back\2' 

- name: Install pout2mzid dependencies
  apt: pkg={{ item }} state=installed
  with_items: "{{ pout2mzid_deps }}"

- name: Install msstitch dependencies
  apt: pkg={{ item }} state=installed
  with_items: "{{ msstitch_deps }}"

- name: Install msstitch libraries from mirror
  pip: name={{ item }} state=present extra_args="--index-url=http://{{ mirror_ip}}/pypimirror/simple"
       executable=pip3
  with_items: "{{ msstitch_pip_deps }}"
  when: use_mirror is defined and use_mirror
- name: Install msstitch libraries from internet
  pip: name={{ item }} state=present executable=pip3
  with_items: "{{ msstitch_pip_deps }}"
  when: use_mirror is not defined or not use_mirror

- name: Install msgfplus dependencies
  apt: pkg={{ item }} state=installed
  with_items: "{{ msgfplus_deps }}"

- name: Install OpenMS dependencies
  apt: pkg={{ item }} state=installed
  with_items: "{{ openms_deps }}"
