---
# NFS Fileserver tasks
- name: Create galaxy user
  user: name=galaxy uid=1001
  
- name: Install fileserver packages
  apt: pkg={{ item }} state=installed
  with_items: fileserver_packages

- name: Create data share path
  file: path={{ datasharepath }} state=directory

- name: Add datashare to NFS exports
  lineinfile: dest=/etc/exports state=present
              regexp="^{{ datasharepath }}"
              line="{{ datasharepath }}    *(rw,sync,no_root_squash,subtree_check,no_wdelay)"

- name: Restart NFS
  service: name=nfs-kernel-server state=restarted
