---
- name: Create postgres galaxy user
  postgresql_user: name=galaxy 
                   password={{ galaxy_pg_pass }} 
                   login_user=postgres
  sudo_user: postgres

- name: Create galaxy db
  postgresql_db: name=galaxy_adapt 
                 owner=galaxy 
                 login_user=postgres
  sudo_user: postgres

- name: Create galaxy ftp postgres user
  postgresql_user: name=galaxyftp
                   password={{ galaxyftp_pg_pass }} 
                   login_user=postgres
  sudo_user: postgres

# Install galaxy
- name: Checkout galaxy from bitbucket
  hg: repo={{ galaxy_repo }} dest={{ galaxy_path }}

- name: Fix ownership of galaxy
  file: path={{ galaxy_path }} owner=galaxy group=galaxy recurse=yes state=directory

- name: Put universe_wsgi file in place
  template: src=universe_wsgi.j2
            dest={{ galaxy_path }}/universe_wsgi.ini
  sudo_user: galaxy

- name: Fetch python eggs
  command: python scripts/fetch_eggs.py chdir={{ galaxy_path }}
  sudo_user: galaxy

- name: Create galaxy db tables by running script
  command: "{{ galaxy_path }}/create_db.sh"
  sudo_user: galaxy

- name: Set postgres privileges for galaxy ftp user
  postgresql_privs: database=galaxy_adapt
                    state=present
                    privs=SELECT
                    type=table
                    objs=galaxy_user
                    roles=galaxyftp
  sudo_user: postgres

# Galaxy init script
- name: Move init script from galaxy to /etc/init.d
  command: cp {{ galaxy_path }}/contrib/galaxy.debian-init /etc/init.d/galaxy
- name: Fix permissions for init script
  file: path=/etc/init.d/galaxy mode=755
- name: Change path to galaxy in init script
  lineinfile: line="DIR={{ galaxy_path }}"
              regexp="galaxy_dist"
              dest=/etc/init.d/galaxy
- name: Change group init script runs under to galaxy
  lineinfile: line='GROUP="galaxy"'
              regexp="GROUP="
              dest=/etc/init.d/galaxy
- name: Copy environment variable file for galaxy service
  copy: src=galaxy_env dest=/etc/default/galaxy
- name: Source variables in init.d service file
  lineinfile: line="[ -f /etc/default/galaxy ] && . /etc/default/galaxy"
              dest=/etc/init.d/galaxy
              insertbefore=BOF
              state=present
- name: Register galaxy init service
  service: name=galaxy enabled=yes

# Conf.xml files
- name: Upload tool_conf.xml file
  copy: src=tool_conf.xml 
        dest={{ galaxy_path }}/tool_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload shed_tool_conf.xml
  copy: src=shed_tool_conf.xml
        dest={{ galaxy_path }}/shed_tool_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload migrated_tools_conf.xml
  copy: src=migrated_tools_conf.xml
        dest={{ galaxy_path }}/migrated_tools_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload datatypes_conf.xml
  copy: src=datatypes_conf.xml
        dest={{ galaxy_path }}/datatypes_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload tool_sheds_conf.xml
  copy: src=tool_sheds_conf.xml
        dest={{ galaxy_path }}/tool_sheds_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload tool_data_table_conf.xml
  copy: src=tool_data_table_conf.xml
        dest={{ galaxy_path }}/tool_data_table_conf.xml
        owner=galaxy
        group=galaxy
- name: Upload shed_tool_data_table_conf.xml
  copy: src=shed_tool_data_table_conf.xml
        dest={{ galaxy_path }}/shed_tool_data_table_conf.xml
        owner=galaxy
        group=galaxy
