---
- name: Fetch python eggs
  command: python scripts/fetch_eggs.py chdir={{ galaxy_path }}
  sudo_user: galaxy

- name: Create bogus galaxy upload dir for nginx which is not on the fileserver
  file: path={{ data_path }}/upload_store state=directory
- name: Adding nginx configuration file
  copy: src=nginx.conf dest=/opt/nginx/conf/nginx.conf

- name: Create galaxy db tables by running script
  command: "{{ galaxy_path }}/create_db.sh"
  sudo_user: galaxy

- name: Set postgres privileges for galaxy ftp user
  postgresql_privs: database=galaxy_adapt
                    state=present
                    privs=SELECT
                    type=table
                    objs=galaxy_user
                    roles=galaxyftp
  sudo_user: postgres

# Galaxy init script
- name: Move init script from galaxy to /etc/init.d
  command: cp {{ galaxy_path }}/contrib/galaxy.debian-init /etc/init.d/galaxy
- name: Fix permissions for init script
  file: path=/etc/init.d/galaxy mode=755
- name: Change path to galaxy in init script
  lineinfile: line="DIR={{ galaxy_path }}"
              regexp="galaxy_dist"
              dest=/etc/init.d/galaxy
- name: Change group init script runs under to galaxy
  lineinfile: line='GROUP="galaxy"'
              regexp="GROUP="
              dest=/etc/init.d/galaxy
- name: Copy environment variable file for galaxy service
  copy: src=galaxy_env dest=/etc/default/galaxy
- name: Source variables in init.d service file
  lineinfile: line="[ -f /etc/default/galaxy ] && . /etc/default/galaxy"
              dest=/etc/init.d/galaxy
              insertbefore=BOF
              state=present
- name: Register galaxy init service
  service: name=galaxy enabled=yes

