---
# Installs percolator, percolator converters, and pout2mzid

- name: Install percolator build packages
  apt: pkg={{ item }} state=installed
  with_items: percolator_build_packages

# Percolator
- name: Get percolator source 
  get_url: url={{ percolator_url }} dest=/tmp/percolator.tar.gz 
- name: Create percolator tool path
  file: path={{ tool_path }}/{{ percolator_path}}/bin state=directory
- name: Untar source
  command: tar xvfz percolator.tar.gz chdir=/tmp/
- name: Cmake percolator
  command: cmake -DTARGET_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX={{ tool_path }}/{{ percolator_path }} -DXML_SUPPORT=ON /tmp/{{ percolator_src }} chdir={{ tool_path }}/{{ percolator_path }}
- name: Make percolator
  command: make -j 4 chdir={{ tool_path }}/{{ percolator_path }}
- name: Make install percolator
  command: make install chdir={{ tool_path }}/{{ percolator_path }}
- include: ../../../misc/tool_dependency_fixer.yml toolpath={{ tool_path }}/{{ percolator_path }}/bin envdest={{ tool_path }}/{{ percolator_path }} toolroot={{ tool_path }}/{{ percolator_pkg }} ldline="#"

# percolator converters
- name: Create percolator converter tool path
  file: path={{ tool_path }}/{{ perconvert_path}}/bin state=directory
- name: Cmake percolator converters
  command: cmake -DTARGET_ARCH=amd64 -DCMAKE_INSTALL_PREFIX={{ tool_path }}/{{ perconvert_path }} -DCMAKE_BUILD_TYPE=Release -DSERIALIZE="TokyoCabinet" /tmp/{{ percolator_src }}/src/converters chdir={{ tool_path }}/{{ perconvert_path }}
- name: Make percolator converters
  command: make chdir={{ tool_path }}/{{ perconvert_path }}
- name: Make install percolator converters
  command: make install chdir={{ tool_path }}/{{ perconvert_path }}
- include: ../../../misc/tool_dependency_fixer.yml toolpath={{ tool_path }}/{{ perconvert_path }}/bin envdest={{ tool_path }}/{{ perconvert_path}} toolroot={{ tool_path }}/{{ perconvert_pkg }} ldline="#"

# Pout2mzid
- name: Create pout2mzid tool path
  file: path={{ pout2mzid_loc }}/bin state=directory
- name: Get pout2mzid source
  git: repo={{ pout2mzid_repo }} version={{ pout2mzid_commit }} dest=/tmp/pout2mzid_src
- name: Cmake pout2mzid
  command: cmake /tmp/pout2mzid_src/CMakeLists.txt -B chdir={{ pout2mzid_loc }}/bin
- name: Make pout2mzid
  command: make chdir={{ pout2mzid_loc }}/bin
- include: ../../../misc/tool_dependency_fixer.yml toolpath={{ pout2mzid_loc }}/bin envdest={{ pout2mzid_loc }} toolroot={{ tool_path }}/{{ pout2mzid_pkg }} ldline="#"
