---

slurm_packages:
  - munge
  - slurm-wlm
  - libslurm-dev 
  - autoconf
  - automake
  - libtool 
  - m4
  - bison
  - gperf
  - ragel

slurm_drmaa_packages:
  - build-essential

slurm_drmaa_repo: https://github.com/natefoo/slurm-drmaa
slurm_drmaa_branch: slurm-drmaa-1.2.0
