---

- name: Install NFS
  apt: name={{ item }} state=installed
  with_items:
  - nfs-common

- name: Create mount points
  file: path={{ item }} state=directory
  with_items: mount_paths

- name: Mount data, tool, galaxy, ftp volumes
  mount: src={{ item.0 }} name={{ item.1 }} fstype=nfs state=mounted opts=defaults
  with_together:
  - mount_shares
  - mount_paths
