---

galaxy_repo: https://github.com/galaxyproject/galaxy
galaxy_revision: master 


galaxy_packages:
  - unzip
  - supervisor
  - git-core
  - uwsgi
  - uwsgi-plugin-python


cleanup_scripts:
  - "{{ galaxy_path }}/scripts/cleanup_datasets/delete_userless_histories.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_histories.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_libraries.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_folders.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_datasets.sh"
