---

galaxy_repo: https://github.com/galaxyproject/galaxy
galaxy_revision: release_17.05


galaxy_packages:
  - virtualenv
  - unzip
  - supervisor
  - git-core

galaxy_pip:
  - uwsgi


cleanup_scripts:
  - "{{ galaxy_path }}/scripts/cleanup_datasets/delete_userless_histories.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_histories.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_libraries.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_folders.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_datasets.sh"
