---

galaxy_repo: https://bitbucket.org/glormph/adapt

galaxy_packages:
  - unzip
  - mercurial
  - python-pip
  - libpq-dev # for ansible postgres stuff

python_libraries:
  - psycopg2 # for setting postgres privileges
