---

galaxy_repo: https://bitbucket.org/glormph/adapt
galaxy_revision: 1cefe97bd46f 


galaxy_packages:
  - unzip
  - mercurial
  - python-pip


cleanup_scripts:
  - "{{ galaxy_path }}/scripts/cleanup_datasets/delete_userless_histories.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_histories.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_libraries.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_folders.sh"
  - "{{ galaxy_path }}/scripts/cleanup_datasets/purge_datasets.sh"
