---
# Installs or updates tools, galaxy

- hosts:
  - master
  - workers
  user: admin
  sudo: True
  roles:
  - tool_dependencies
 

- hosts: master
  user: admin
  sudo: True
  vars_files:
  - credentials/user_data.yml
  roles:
  - proteowizard
  - msgfplus
  - percolator
  - openms
  - proteinquant
  - msstitch
  tasks:
  - name: Fix ownership of all tools
    file: path={{ tool_path }} owner=galaxy group=galaxy recurse=yes state=directory
