---

- name: Install protein quant build packages
  apt: pkg={{ item }} state=installed
  with_items: protquant_build_packages 

- name: Create protein quant tool path
  file: path={{ protquant_loc }} state=directory
- name: Get protein quant 
  git: repo=https://github.com/glormph/protein-quant version={{ protquant_git_ver }} dest={{ protquant_loc }}

- include: ../../../tasks/tool_dependency_fixer.yml toolpath={{ protquant_loc }} envdest={{ protquant_loc }} toolroot={{ tool_path }}/{{ protquant_pkg }} ldline="#"
