---

- name: Install openMS build packages
  apt: pkg={{ item }} state=installed
  with_items: openms_build_packages

- name: Install OpenMS dependencies
  apt: pkg={{ item }} state=installed
  with_items: openms_deps

- name: Create OpenMS tool path
  file: path={{ openms_loc }} state=directory
- name: Get OpenMS source
  git: repo=https://github.com/OpenMS/OpenMS.git version={{ openms_git_ver }} dest={{ openms_loc }}
- name: Get OpenMS contrib
  git: repo=https://github.com/OpenMS/contrib.git
       dest={{ openms_loc }}/contrib
- name: Build SEQAN for OpenMS
  command: cmake -DBUILD_TYPE=SEQAN .
           chdir={{ openms_loc }}/contrib
- name: Build WildMagic5 for OpenMS
  command: cmake -DBUILD_TYPE=WILDMAGIC .
           chdir={{ openms_loc }}/contrib
#- name: Softlink libbz2, libxerces2 libraries 
#  file: src={{ item.0 }} dest={{ item.1 }} state=link
#  with_together:
#  - ['/usr/lib/x86_64-linux-gnu/libxerces-c.so', '/usr/lib/x86_64-linux-gnu/libxerces-c.a']
#  - ['/usr/local/lib/libxerces-c.so', '/usr/local/lib/libxerces-c.a']
- name: cmake OpenMS
  command: cmake -DCMAKE_PREFIX_PATH="{{ openms_loc }}/contrib" -DBOOST_USE_STATIC=OFF -DSEQAN_INCLUDE_DIR="{{ openms_loc }}/contrib/include" -DWM5_INCLUDE_DIR="{{ openms_loc }}/contrib/include/WildMagic" . 
           chdir={{ openms_loc }}
- name: make OpenMS
  command: make chdir={{ openms_loc }}
- include: ../../tools/tasks/tool_dependency_fixer.yml toolpath={{ openms_loc }}/bin envdest={{ openms_loc }} toolroot={{ tool_path }}/{{ openms_pkg }} ldline="LD_LIBRARY_PATH="{{ openms_loc }}/lib:$LD_LIBRARY_PATH""  
