---

- name: Install msstitch build packages
  apt: pkg={{ item }} state=installed
  with_items: msstitch_build_packages 

- name: Create msstitch tool path
  file: path={{ msstitch_loc }} state=directory

- name: Get msstitch 
  git: repo=https://github.com/glormph/msstitch version={{ msstitch_git_ver }} dest={{ msstitch_loc }}

- include: ../../tools/tasks/tool_dependency_fixer.yml toolpath={{ msstitch_loc }} envdest={{ msstitch_loc }} toolroot={{ tool_path }}/{{ msstitch_pkg }} ldline="#"
