---
# Slurm-drmaa, only on master

- name: Install drmaa packages
  apt: pkg={{ item }} state=installed
  with_items: "{{ slurm_drmaa_packages }}"


- name: Create Slurm drmaa path in case it doesnt exist
  file: path=/tmp/slurm-drmaa state=directory
- name: Get slurm-drmaa source
  git: repo={{ slurm_drmaa_repo }} version={{ slurm_drmaa_branch }} dest=/tmp/slurm-drmaa
- name: Configure slurm-drmaa
  command: ./autogen.sh --with-slurm-inc=/usr/include/slurm --with-slurm-lib=/usr/lib CPPFLAGS="-g"
           chdir=/tmp/slurm-drmaa
- name: Make slurm-drmaa
  command: make
           chdir=/tmp/slurm-drmaa
- name: Make install slurm-drmaa
  command: make install
           chdir=/tmp/slurm-drmaa
