---
# Setting up slurm-llnl

- name: Set hostnames explicitly
  template: src=hostname.j2 dest=/etc/hostname

- name: Change /etc/hosts for hostname
  lineinfile: dest=/etc/hosts line="127.0.1.1       {{ inventory_hostname }}" regexp="^127.0.1.1"

- name: Check if mungekey is made
  local_action: stat path=credentials/{{ mungekey_file }}
  register: mungekey_stat
- name: Create mungekey
  local_action: shell dd if=/dev/urandom bs=1 count=1024 > credentials/{{ mungekey_file }}
  when: mungekey_stat.stat.exists == false

- name: Install SLURM
  apt: pkg={{ item }} state=installed
  with_items: slurm_packages

- include: drmaa.yml # only compile slurm-drmaa when on master
  when: "'master' in group_names"

- name: Set permissions on /etc
  file: path=/etc state=directory mode=0755
- name: Create munge conf dir
  file: path=/etc/munge state=directory
- name: Put munge key in place 
  copy: src=credentials/{{ mungekey_file }} dest=/etc/munge/munge.key owner=munge mode=0600
- name: Modify hosts file for munge
  lineinfile: "dest=/etc/hosts line='{{ ansible_eth0.ipv4.address }}    {{ ansible_hostname }}'"
- name: Chmod log dir for munge
  file: path=/var/log/munge state=directory mode=0711
- name: Chmod /var/log for munge
  file: path=/var/log state=directory mode=0755

- name: Setup slurm user
  user: name=slurm state=present
- name: Setup slurm config dir
  file: path=/etc/slurm-llnl state=directory mode=0755 owner=root group=root
- name: Put slurm config file in place
  template: src=slurm_conf.j2 dest=/etc/slurm-llnl/slurm.conf owner=slurm mode=0755
