---

- name: Install build packages
  apt: pkg={{ item }} state=installed
  with_items: hardklor_bullseye_pkg

- name: Download hardklor, bullseye, kronik zips
  get_url: url={{ item.0 }}
           dest={{ item.1 }}
  with_together:
  - zipurls
  - zipdests  

- name: Create tool paths
  file: path={{ item }} state=directory
  with_items:
  - "{{ hardklor_path }}/bin"
  - "{{ bullseye_path }}/bin"
  - "{{ kronik_path }}/bin"
  - "{{ kronik_tmp_path }}"

- name: Unzip hardklor
  unarchive: src={{ item.0 }}
             dest={{ item.1 }}
             copy=no
  with_together:
  - zipdests
  - tooldests

- name: Pick correct kronik executable
  command: mv {{ kronik_tmp_path }}/linux64/kronik {{ kronik_path }}/bin/kronik
           creates="{{ kronik_path }}/bin/kronik"
           removes="{{ kronik_tmp_path }}/linux64/kronik"

- name: Make binaries executable
  file: path={{ item }} mode=0755
  with_items:
  - "{{ hardklor_path }}/bin/hardklor"
  - "{{ bullseye_path }}/bin/bullseye_lin64_130"
  - "{{ kronik_path }}/bin/kronik"

- include: ../../../tasks/tool_dependency_fixer.yml 
           toolpath=/{{ hardklor_path }}/bin
           envdest=/{{ hardklor_path }}
           toolroot={{ tool_path }}/{{ hardklor_pkg }} ldline="#"

- include: ../../../tasks/tool_dependency_fixer.yml 
           toolpath=/{{ kronik_path }}/bin
           envdest=/{{ kronik_path }}
           toolroot={{ tool_path }}/{{ kronik_pkg }} ldline="#"

- include: ../../../tasks/tool_dependency_fixer.yml 
           toolpath=/{{ bullseye_path }}/bin
           envdest=/{{ bullseye_path }}
           toolroot={{ tool_path }}/{{ bullseye_pkg }} ldline="#"
