---
# tool dependencies

percolator_deps:
  - xsdcxx 
  - libxerces-c-dev
  - libboost-dev
  - libboost-filesystem-dev
  - libboost-system-dev
  - libboost-thread-dev
  - libsqlite3-dev
  - libtokyocabinet-dev
  - zlib1g-dev
  - libbz2-dev

pout2mzid_deps:
  - libxerces-c-dev
  - libboost-dev
  - libboost-program-options-dev
  - libboost-filesystem-dev
  - libboost-system-dev
  - xsdcxx

msstitch_deps:
  - python3
  - python3-pip
  - python3-dev
  - libxml2-dev
  - libxslt1-dev
  - python3-numpy

msstitch_pip_deps:
 - pyyaml
 - lxml
 - numpy
 - biopython
 - simplejson

msgfplus_deps:
  - default-jdk

openms_deps:
  - qt4-dev-tools
  - libxerces-c-dev
  - libgsl0-dev
  - libboost-regex-dev
  - libboost-iostreams-dev
  - libboost-date-time-dev
  - libboost-math-dev
  - libsvm-dev
  - libglpk-dev
  - libzip-dev
  - zlib1g-dev
  - libbz2-dev 
  - libeigen3-dev
