---
# Installation of tools for galaxy. In future, from toolshed!

# MSGF+ installation
- name: Fetch MSGFPlus java package
  get_url: url={{ msgf_url }} dest=/tmp/msgfplus.zip
- name: Unzip MSGFPlus
  command: unzip /tmp/msgfplus.zip MSGFPlus.jar -d /tmp/ creates=/tmp/MSGFPlus.jar
- name: Create msgf tool path
  file: path={{ tool_path }}/{{ msgf_pkg }}/{{ msgf_ver }} state=directory
- name: Install MSGFPlus
  command: mv /tmp/MSGFPlus.jar {{ tool_path }}/{{ msgf_pkg }}/{{ msgf_ver }}
- include: tool_dependency_fixer.yml toolpath={{ tool_path }}/{{ msgf_pkg }}/{{ msgf_ver }} envdest={{ tool_path }}/{{ msgf_pkg }}/{{ msgf_ver }} toolroot={{ tool_path }}/{{ msgf_pkg }} ldline="#"

# Percolator installation, first fix new cmake version
- name: Get newer cmake version
  get_url: url=http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz dest=/tmp/cmake.tar.gz
- name: Unpack newer cmake
  command: tar xvfz /tmp/cmake.tar.gz chdir=/tmp
- name: Bootstrap cmake
  command: ./bootstrap chdir=/tmp/cmake-2.8.12
- name: Build cmake
  command: make -j 4 chdir=/tmp/cmake-2.8.12
- name: Install cmake
  command: make install chdir=/tmp/cmake-2.8.12
#### TODO remove previous block when cmake is updated in apt repo

# Percolator
- name: Get percolator source 
  get_url: url={{ percolator_url }} dest=/tmp/percolator.tar.gz 
- name: Create percolator tool path
  file: path={{ tool_path }}/{{ percolator_path}} state=directory
- name: Untar source
  command: tar xvfz percolator.tar.gz chdir=/tmp/
- name: Cmake percolator
  command: cmake -DTARGET_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX={{ tool_path }}/{{ percolator_path }} -DXML_SUPPORT=ON /tmp/{{ percolator_src }} chdir={{ tool_path }}/{{ percolator_path }}
- name: Make percolator
  command: make -j 4 chdir={{ tool_path }}/{{ percolator_path }}
  command: make -j 4 package chdir={{ tool_path }}/{{ percolator_path }}
- include: tool_dependency_fixer.yml toolpath={{ tool_path }}/{{ percolator_path }}/bin envdest={{ tool_path }}/{{ percolator_path }} toolroot={{ tool_path }}/{{ percolator_pkg }} ldline="#"

# percolator converters
- name: Create percolator converter tool path
  file: path={{ tool_path }}/{{ perconvert_path}} state=directory
- name: Cmake percolator converters
  command: cmake -DTARGET_ARCH=amd64 -DCMAKE_INSTALL_PREFIX={{ tool_path }}/{{ perconvert_path }} -DCMAKE_BUILD_TYPE=Release -DSERIALIZE="TokyoCabinet" /tmp/{{ percolator_src }}/src/converters chdir={{ tool_path }}/{{ perconvert_path }}
- name: Make percolator converters
  command: make -j 4 chdir={{ tool_path }}/{{ perconvert_path }}
  command: make -j 4 package chdir={{ tool_path }}/{{ perconvert_path }}
- include: tool_dependency_fixer.yml toolpath={{ tool_path }}/{{ perconvert_path }}/bin envdest={{ tool_path }}/{{ perconvert_path}} toolroot={{ tool_path }}/{{ perconvert_pkg }} ldline="#"
# FIXME check if ldline works!

# Pycolator installation
- name: Create pycolator tool path
  file: path={{ tool_path }}/{{ pycolator_pkg }}/{{ pycolator_ver }} state=directory
- name: Git checkout pycolator
  git: repo=git://github.com/glormph/pycolator.git dest={{ tool_path }}/{{ pycolator_pkg }}/{{ pycolator_ver }}
- name: Change pycolator.py to executable
  file: path={{ tool_path }}/{{ pycolator_pkg }}/{{ pycolator_ver }}/pycolator.py mode=755
- include: tool_dependency_fixer.yml toolpath={{ tool_path }}/{{ pycolator_pkg }}/{{ pycolator_ver }} envdest={{ tool_path }}/{{ pycolator_pkg }}/{{ pycolator_ver }} toolroot={{ tool_path }}/{{ pycolator_pkg }} ldline="#"  


- name: Fix ownership of all tools
  file: path={{ tool_path }} owner=galaxy group=galaxy recurse=yes state=directory


