---
# Admin user should be present, uid 1000, and no other users on the master

# Master preparation tasks to make it a mirror
- name: Setup galaxy user
  user: name=galaxy comment="Galaxy user" uid=1001 state=present shell=/bin/bash
- name: Create galaxy mount point for nginx and other mount points
  file: path={{ item }} state=directory
  with_flattened: mount_paths
  
- name: Install packages required for building
  apt: pkg={{ item }} state=installed
  with_items: build_packages # from core vars file

# Prepare munge key
- name: Create mungekey
  shell: dd if=/dev/urandom bs=1 count=1024 >/home/admin/mungekey

