---

- name: Create galaxy user
  user: name=galaxy state=present
  
- name: Install galaxy dependencies
  apt: pkg={{ item }} state=installed
  with_items: "{{ galaxy_packages }}"

- name: Create galaxy path in case it doesnt exist
  file: path={{ item }} state=directory owner=galaxy group=galaxy
  with_items: 
    - "{{ galaxy_path }}"
    - "{{ ftp_path }}"

- name: Checkout galaxy from github 
  git: repo={{ galaxy_repo }} version={{ galaxy_revision }} dest={{ galaxy_path }}
  become_user: galaxy

- name: Install crontab to keep datasets clean
  cron: name="cleanup datasets"
        user=galaxy
        hour=7
        job="{{ cleanup_scripts|join(' && ') }}"

- name: Install remaining packages in venv (i.e. uwsgi)
  pip: name={{ item }} virtualenv={{ galaxy_path }}/.venv
  with_items: "{{ galaxy_pip }}"
  become_user: galaxy

- name: Move supervisor configuration
  template: src=supervisord.conf.j2
            dest=/etc/supervisor/supervisord.conf
