---

- name: Install galaxy dependencies
  apt: pkg={{ item }} state=installed
  with_items: galaxy_packages

- name: Create galaxy-dist
  file: path={{ galaxy_share_dir }} owner=galaxy group=galaxy state=directory

- name: Add galaxy share to NFS exports template
  lineinfile: dest=/etc/exports state=present
              regexp="^{{ galaxy_share_dir }}"
              line="{{ galaxy_share_dir }}    *(rw,sync,no_root_squash,subtree_check,no_wdelay)"

- name: Restart NFS
  service: name=nfs-kernel-server state=restarted

- name: Checkout galaxy from github 
  git: repo={{ galaxy_repo }} version={{ galaxy_revision }} dest={{ galaxy_share_dir }}
  sudo_user: galaxy

- name: Put galaxy.ini file in place
  template: src=galaxy.ini.j2
            dest={{ galaxy_share_dir }}/config/galaxy.ini
  sudo_user: galaxy

- name: Install crontab to keep datasets clean
  cron: name="cleanup datasets"
        user=galaxy
        hour=7
        job="{{ cleanup_scripts|join(' && ') }}"

# Conf.xml files
- name: Upload tool_conf.xml file
  copy: src=tool_conf.xml 
        dest={{ galaxy_share_dir }}/config/tool_conf.xml
        owner=galaxy
        group=galaxy
#- name: Upload shed_tool_conf.xml
#  copy: src=shed_tool_conf.xml
#        dest={{ galaxy_share_dir }}/shed_tool_conf.xml
#        owner=galaxy
#        group=galaxy
#- name: Upload migrated_tools_conf.xml
#  copy: src=migrated_tools_conf.xml
#        dest={{ galaxy_share_dir }}/migrated_tools_conf.xml
#        owner=galig/y
#        group=galaxy
- name: Upload datatypes_conf.xml
  copy: src=datatypes_conf.xml
        dest={{ galaxy_share_dir }}/config/datatypes_conf.xml
        owner=galaxy
        group=galaxy
#- name: Upload tool_sheds_conf.xml
#  copy: src=tool_sheds_conf.xml
#        dest={{ galaxy_share_dir }}/tool_sheds_conf.xml
#        owner=galaxy
#        group=galaxy
#- name: Upload tool_data_table_conf.xml
#  copy: src=tool_data_table_conf.xml
#        dest={{ galaxy_share_dir }}/tool_data_table_conf.xml
#        owner=galaxy
#        group=galaxy
#- name: Upload shed_tool_data_table_conf.xml
#  copy: src=shed_tool_data_table_conf.xml
#        dest={{ galaxy_share_dir }}/shed_tool_data_table_conf.xml
#        owner=galaxy
#        group=galaxy

- name: Run common_startup.sh to fetch wheels
  command: "{{ galaxy_share_dir }}/scripts/common_startup.sh"
  sudo_user: galaxy

- name: Create galaxy db tables by running script
  command: "{{ galaxy_share_dir }}/create_db.sh"
  sudo_user: galaxy

- name: Move supervisor configuration
  template: src=supervisord.conf.j2
            dest=/etc/supervisord.conf

- name: Restart supervisor
  supervisorctl: name=galaxy: state=started
