---
# Playbook to install fileserver, master and worker tools

## Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
    - private_ip
    - update
    - fileserver

# Reboot fileserver
- hosts: fileserver
  sudo: true
  user: admin
  roles:
    - reboot

# Install tool dependencies, slurm, fstab data
- hosts:
  - master_private
  - workers
  vars_files:
    - inventory/cluster_data.yml
  vars:
    - has_fileserver: true
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - core

# Mount tool and galaxy volume via fstab
- hosts:
  - workers
  user: admin
  sudo: true
  roles:
    - worker

# Install tools and other master things (Postgres, proFTPd, galaxy, etc)
- hosts: master_private
  vars_files:
    - roles/master/vars/tools.yml
    - roles/core/vars/main.yml
  sudo: true
  roles:
    - master
    - galaxy_initialization

# Reboot master
- hosts:
  - master_private
  sudo: true
  user: admin
  roles:
    - reboot

# Reboot workers
- hosts:
  - workers
  sudo: true
  user: admin
  roles:
    - reboot
