---
# Playbook to install fileserver, master and worker tools

# Ubuntu 14.04 demanded
# Make sure you have a mirror host with updated deb and pypi mirrors. There is a playbook for that too, run it first
# Workers and master should be on a private network. At least master needs also a non private network
# Master and workers should have admin, uid=1000, no other users
# admin should have passless ssh-key to login to workers

# Get hostvars for all boxes
- hosts:
  - webserver
  - ftpserver
  - dbserver
  - toolserver
  - fileserver
  - workers
  - mirror
  user: admin
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"


- hosts:
  - webserver
  - ftpserver
  - dbserver
  - toolserver
  - fileserver
  - workers
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - ntp
  - core

# Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
  - fileserver

- hosts: dbserver
  user: admin
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  roles:
  - postgres


- hosts: ftpserver
  user: admin
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  roles:
  - proftpd 

- hosts:
  - toolserver
  user: admin
  sudo: true
  roles:
  - tools


# Install webserver
- hosts: webserver
  user: admin
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  - credentials/user_data.yml
  roles:
  - slurm
  - galaxy
  - mount_shares 
  - nginx 


# Single task to set privileges on postgres table has to be done after
# tables are initialized, which must be done after DBserver is installed
- hosts: dbserver
  user: admin
  sudo: true
  tasks:
  - name: Set postgres privileges for galaxy ftp user
    postgresql_privs: database=galaxy_adapt
                      state=present
                      privs=SELECT
                      type=table
                      objs=galaxy_user
                      roles=galaxyftp
    sudo_user: postgres


# Install slurm, fstab data
- hosts:
  - workers
  user: admin
  sudo: true
  roles:
  - slurm
  - mount_shares


# Reboot all
- hosts:
  - master
  - workers
  sudo: true
  user: admin
  roles:
  - reboot
