---
# Playbook to install fileserver, master and worker tools

# Ubuntu 14.04 demanded
# Make sure you have a master with deb and pypi mirrors
# Workers and master should be on a private network. At least master needs also a non private network
# Master and workers should have admin, uid=1000, no other users
# admin should have passless ssh-key to login to workers

# Prepare master web host first, to be able to host mirrors
- hosts: master
  user: admin
  sudo: True
  roles:
  - update
  - nginx


# Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - fileserver
  - reboot # rebooting can take too long if slow boot and fast next play


# Install tool dependencies, slurm, fstab data
- hosts:
  - master
  - workers
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - core
  - slurm
  - tool_dependencies


# Install tools and other master things (Postgres, proFTPd, galaxy, etc)
- hosts: master
  vars_files:
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  roles:
  - tools ## FIXME merge with tool_deps role
  - postgres_proftpd
  - galaxy_initialization

# Reboot workers
- hosts:
  - workers
  sudo: true
  user: admin
  roles:
  - reboot
