---
# Playbook to install fileserver, master and worker tools

# Before other things, master and worker should have:
# ubuntu 14.04 install
# admin user with uid 1000, no other users
# passless(?) key based access to admin account


# Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
  - update
  - fileserver
  - reboot


# Update boxes and install core stuff
- hosts:
  - master
  - workers
  user: admin
  sudo: True
  roles:
  - update
  - core
  - slurm
  - tool_dependencies


# Master specific things
- hosts: master
  user: admin
  sudo: True
  vars_files:
  - credentials/dbpass.yml
  roles:
  - nginx
  - tools
  - postgres_proftpd
  - galaxy
  - galaxy_initialization
  - reboot

# Reboot workers
- hosts: workers
  user: admin
  sudo: True
  roles:
  - reboot
