---

## Before other things, master and worker should have:
# ubuntu install
# admin user with uid 1000, no other users
# key based access to admin account

# Init, munge key creation
- hosts:
  - master
  user: admin
  tasks:
  - name: Check if mungekey is made
    local_action: stat path=credentials/{{ mungekey_file }}
    register: mungekey_stat
  - name: Create mungekey
    local_action: shell dd if=/dev/urandom bs=1 count=1024 > credentials/{{ mungekey_file }}
    when: mungekey_stat.stat.exists == false


# Update boxes and install core stuff
- hosts:
  - master
  - worker
  user: admin
  sudo: True
  vars_files:
    - inventory/test_env_cluster_data.yml
  roles:
  - update
  - core
  handlers:
  - include: handlers/handlers.yml

# Master specific things
- hosts: master
  user: admin
  sudo: True
  roles:
  - nginx
  - master
  - tools
  handlers:
  - include: handlers/handlers.yml

# Worker
- hosts: worker
  user: admin
  sudo: True
  roles:
  - worker
  handlers:
  - include: handlers/handlers.yml

# Reboots
- hosts:
  - master
  - worker
  user: admin
  sudo: True
  roles:
  - reboot
