---
# Playbook to install fileserver, master and worker tools

# Ubuntu 14.04 demanded
# Make sure you have a mirror host with updated deb and pypi mirrors. There is a playbook for that too, run it first
# Workers and master should be on a private network. At least master needs also a non private network
# Master and workers should have admin, uid=1000, no other users
# admin should have passless ssh-key to login to workers

# Get hostvars for all boxes
- hosts:
  - master
  - fileserver
  - workers
  - mirror
  user: admin
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"


- hosts:
  - fileserver
  - workers
  user: admin
  sudo: true
  tasks:
  - name: Fix etc/hosts for gluster
    lineinfile: dest=/etc/hosts regexp='^{{ item }}'
                line="{{ hostvars[item][hostvars[item]['private_ip_port']]['ipv4']['address'] }}	{{ item }}"
    with_items: 
    - "{{ groups['fileserver'] }}"
    - "{{ groups['workers'] }}"


# Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - fileserver
  - ntp
  - reboot


# Install tool dependencies, slurm, fstab data
- hosts:
  - master
  - workers
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - core
  - ntp
  - slurm


# Install master things (Postgres, proFTPd, galaxy, etc)
- hosts: master
  user: admin
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  - credentials/user_data.yml
  roles:
  - postgres_proftpd
  - galaxy
  - nginx
  - galaxy_initialization


# Reboot all
- hosts:
  - master
  - workers
  sudo: true
  user: admin
  roles:
  - reboot
