---
# Playbook to install fileserver, master and worker tools

## Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
    - private_ip
    - update
    - fileserver

# Install tool dependencies and mount volumes
- hosts:
  - master_private
  - workers
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - core

# Install tools and other master things (Postgres, proFTPd, galaxy, etc)
- hosts: master_private
  vars_files:
    - roles/master/vars/tools.yml
    - roles/core/vars/main.yml
  sudo: true
  roles:
  - master

# Reboot remote systems
- hosts:
  - workers
  - fileserver
  sudo: true
  tasks:
    - name: Reboot system after provision
      command: /sbin/reboot
