---

# Install a new worker
# This also updates the rest of the cluster, so that each worker
# has the same package versions installed.
#
# Needs to be called with --extra-vars '{"new_workers": ["your_new_worker_name", "second_new_worker"]}'
 
- hosts: 
  - workers
  sudo: True
  tasks:
  - name: Shutdown SLURM in workers
    service: name=slurm-llnl state=stopped
    when: inventory_hostname not in new_workers

- hosts: 
  - fileserver
  - mirror
  sudo: True
  tasks:
  - name: Dummy task to get fileserver info
    debug: msg="Connected to fileserver"

- hosts: 
  - master
  sudo: True
  roles:
  - shutdown_services

- hosts:
  - master
  - workers
  sudo: True
  roles:
  - private_ip
  - update
  - core
  - ntp
  - tool_dependencies
  - slurm
