---
# Playbook to install fileserver, master and worker tools on (OpenStack) cloud
# No cloudman (yet), just a mirror of local cluster
#
# Ubuntu 14.04 demanded
# Workers and master should be on a private network. 
# Master and workers should have ubuntu, uid=1000, no other users
# ubuntu should have passless ssh-key (passphrase ok, with ssh-agent) to login to master, workers

# Get hostvars for all boxes
- hosts:
  - webserver
  - ftpserver
  - dbserver
  - toolserver
  - fileserver
  - workers
  become: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"


- hosts:
  - webserver
  - ftpserver
  - dbserver
  - toolserver
  - fileserver
  - workers
  become: true
  roles:
  - update
  - ntp
  - core

# Prepare fileserver
- hosts: fileserver
  become: true
  roles:
  - nfsdata 
  - nfstools
  - nfsgalaxy

- hosts: dbserver
  become: true
  vars_files:
  - credentials/dbpass.yml
  roles:
  - postgres


- hosts:
  - toolserver
  become: true
  roles:
  - nfstools


# Install webserver
- hosts: webserver
  become: true
  vars_files:
  - credentials/dbpass.yml
  - credentials/user_data.yml
  roles:
  - slurm
  - mount_shares 
  - galaxy
  - galaxy-config
  - galaxy-init
  - nginx 

- hosts: ftpserver
  become: true
  vars_files:
  - credentials/dbpass.yml
  roles:
  - mount_shares
  - proftpd 

# Single task to set privileges on postgres table has to be done after
# tables are initialized, which must be done after DBserver is installed
- hosts: dbserver
  become: true
  tasks:
  - name: Set postgres privileges for galaxy ftp user
    postgresql_privs: database=galaxy_adapt
                      state=present
                      privs=SELECT
                      type=table
                      objs=galaxy_user
                      roles=galaxyftp
    become_user: postgres


# Install slurm, fstab data
- hosts:
  - workers
  become: true
  roles:
  - slurm
  - mount_shares


# Reboot all
- hosts:
  - webserver
  - workers
  become: true
  roles:
  - reboot
