---

# Get hostvars for all boxes
- hosts:
  - fileserver
  - workers
  - mirror
  - ftpserver
  - webserver
  - dbserver
  - toolserver
  user: admin
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"


# Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - fileserver
  - ntp
  - core


# Share mounting
- hosts:
  - webserver
  - ftpserver
  - workers
  user: admin
  sudo: true
  roles:
  - core
  - mount_shares
