---

# Get hostvars for all boxes
- hosts:
  - master
  - fileserver
  - workers
  - mirror
  user: admin
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"

# Prepare fileserver
- hosts: fileserver
  user: admin
  sudo: true
  roles:
  - private_ip
  - update
  - fileserver
  - ntp

