---
# Playbook to update a galaxy distribution

- hosts: 
  - webserver
  user: admin
  sudo: True
  tasks:
  - name: Shutdown SLURM and galaxy on master
    service: name={{ item }} state=stopped
    with_items:
    - galaxy
    - slurm-llnl

- hosts: 
  - fileserver
  - toolserver
  - ftpserver
  user: admin
  sudo: True
  tasks:
  - name: Dummy task to get info
    debug: msg="Connected to fileserver"

- hosts: webserver
  user: admin
  sudo: True
  vars_files: 
  - credentials/user_data.yml
  - credentials/dbpass.yml
  roles:
  - galaxy
  - nginx
