---
# Playbook to update a galaxy distribution

- hosts: 
  - fileserver
  - mirror
  - toolserver
  - ftpserver
  user: admin
  sudo: True
  tasks:
  - name: Dummy task to get server info
    debug: msg="Connected to server"

- hosts: 
  - webserver
  user: admin
  sudo: True
  tasks:
  - name: Shutdown SLURM and galaxy on master
    service: name={{ item }} state=stopped
    with_items:
    - galaxy
    - slurm-llnl


- hosts: dbserver
  user: admin
  sudo: True
  vars_files:
  - credentials/dbpass.yml
  roles:
  - postgres
  

- hosts: webserver
  user: admin
  sudo: True
  vars_files: 
  - credentials/user_data.yml
  - credentials/dbpass.yml
  roles:
  - mount_shares
  - galaxy
