---
# Playbook to update a galaxy distribution

- hosts: 
  - fileserver
  - toolserver
  - ftpserver
  become: true
  tasks:
  - name: Dummy task to get server info
    debug: msg="Connected to server"

- hosts: 
  - webserver
  become: true
  tasks:
  - name: Shutdown SLURM on master
    service: name=slurmctld state=stopped
  - name: Shutdown galaxy
    supervisorctl: name="galaxy:" state=stopped



- hosts: dbserver
  become: True
  vars_files:
  - credentials/dbpass.yml
  roles:
  - postgres
  

- hosts: webserver
  become: True
  vars_files: 
  - credentials/user_data.yml
  - credentials/dbpass.yml
  roles:
  - mount_shares
  - galaxy
  - galaxy-config


- hosts: 
  - webserver
  become: true
  tasks:
  - name: Start SLURM on master
    service: name=slurmctld state=started
  - name: Start galaxy
    supervisorctl: name="galaxy:" state=started
