---
# Playbook to update a galaxy distribution

- hosts: 
  - master
  user: admin
  sudo: True
  tasks:
  - name: Shutdown SLURM and galaxy on master
    service: name={{ item }} state=stopped
    with_items:
    - galaxy
    - slurm-llnl

- hosts: 
  - fileserver
  user: admin
  sudo: True
  tasks:
  - name: Dummy task to get fileserver info
    debug: msg="Connected to fileserver"

- hosts: master
  user: admin
  sudo: True
  vars_files: 
  - credentials/user_data.yml
  roles:
  - galaxy

- hosts: master
  user: admin
  sudo: True
  vars_files:
  - credentials/user_data.yml
  tasks:
  - name: Start galaxy and SLURM
    service: name={{ item }} state=started
    with_items:
    - slurm-llnl
    - galaxy
