---
# Playbook to update a galaxy distribution

- hosts: 
  - fileserver
  - toolserver
  - ftpserver
  become: true
  tasks:
  - name: Dummy task to get server info
    debug: msg="Connected to server"

- hosts: 
  - webserver
  become: true
  tasks:
  - name: Shutdown SLURM on master
    service: name={{ item }} state=stopped
    with_items:
    - slurm-llnl
  - name: Shutdown galaxy
    supervisorctl: name="galaxy:" state=stopped


- hosts: webserver
  become: True
  vars_files: 
  - credentials/user_data.yml
  - credentials/dbpass.yml
  roles:
  - galaxy-config


- hosts: 
  - webserver
  become: true
  tasks:
  - name: Start SLURM on master
    service: name={{ item }} state=started
    with_items:
    - slurm-llnl
  - name: Start galaxy
    supervisorctl: name="galaxy:" state=started
