---
# Playbook to install proteomics analysis Galaxy on a single powerful node
# Ubuntu 16.04 
# Node should have one user=ubuntu uid=1000, galaxy will be 1001
# Fill in a DB password in credentials
# Set the name of the ethernet port in the group_vars file single_node

# Get hostvars for all boxes
- hosts:
  - webserver
  - dbserver
  user: ubuntu
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"


# Update apt get
- hosts:
  - webserver
  user: ubuntu
  sudo: true
  roles:
  - update


# Keep as is, even though we dont have to connect over network
# Maybe add local connection later
- hosts: dbserver
  user: ubuntu
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  roles:
  - postgres


# Install webserver
- hosts: webserver
  user: ubuntu
  sudo: true
  vars_files:
  - credentials/dbpass.yml
  - credentials/user_data.yml
  roles:
  - slurm
  - galaxy
  - nginx 


# Reboot single node system
- hosts:
  - webserver
  sudo: true
  user: ubuntu
  roles:
  - reboot
