---
# Playbook to install proteomics analysis Galaxy on a single powerful node
# Assumes Ubuntu 16.04 
# Copy credentials/example.yml to credentials/credentials.yml and fill in a DB password and admins
# Set the name of the ethernet port in the group_vars file single_node

# Get hostvars for all boxes
- hosts:
  - webserver
  - dbserver
  become: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"


# Update apt get
- hosts:
  - webserver
  become: true
  roles:
  - update


# Keep as is, even though we dont have to connect over network
# Maybe add local connection later
- hosts: dbserver
  become: true
  vars_files:
  - credentials/credentials.yml
  roles:
  - postgres


# Install webserver
- hosts: webserver
  become: true
  vars_files:
  - credentials/credentials.yml
  roles:
  - slurm
  - galaxy
  - galaxy-init
  - galaxy-config
  - nginx 


# Reboot single node system
- hosts:
  - webserver
  become: true
  roles:
  - reboot
