---
# Playbook to update a galaxy distribution

- hosts: 
  - webserver
  sudo: True
  tasks:
  - name: Shutdown SLURM and galaxy on master
    service: name={{ item }} state=stopped
    with_items:
    - galaxy
    - slurmctld

- hosts: 
  - workers 
  sudo: True
  tasks:
  - name: Shutdown SLURM 
    service: name=slurmd state=stopped


- hosts:
  - master
  - workers
  sudo: True
  roles:
  - slurm


- hosts: 
  - webserver
  sudo: True
  tasks:
  - name: Shutdown SLURM and galaxy on master
    service: name={{ item }} state=started
    with_items:
    - galaxy
    - slurmctld

- hosts: 
  - workers 
  sudo: True
  tasks:
  - name: Shutdown SLURM 
    service: name=slurmd state=started
