---
# Installs or updates tools, galaxy

# Get hostvars for all boxes
- hosts:
  - master
  - fileserver
  - workers
  - mirror
  user: admin
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"

- hosts:
  - master
  - workers
  user: admin
  sudo: True
  roles:
  - tool_dependencies


- hosts: master
  user: admin
  sudo: True
  tasks:
  - name: Mount tool path and other paths before installing tools
    mount: src={{ item.0 }} name={{ item.1 }} fstype=nfs state=mounted 
    with_together:
    - mount_shares
    - mount_paths
    

- hosts: master
  user: admin
  sudo: True
  vars_files:
  - credentials/user_data.yml
  roles:
  - proteowizard
  - msgfplus
  - percolator
  - openms
  - proteinquant
  - msstitch
  tasks:
  - name: Fix ownership of all tools
    file: path={{ tool_path }} owner=galaxy group=galaxy recurse=yes state=directory
