---
# Installs or updates tools, galaxy

# Get hostvars for all boxes
- hosts:
  - workers
  - toolserver
  - mirror
  - ftpserver
  - fileserver
  become: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"

- hosts:
  - webserver 
  - workers
  become: True
  roles:
  - tool_dependencies


# preparations
- hosts: toolserver
  become: true
  tasks:
  - name: Get github hostkey
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com" 


- hosts: webserver
  become: true
  roles:
  - mount_shares


- hosts: webserver
  become: true
  roles:
  - msgfplus
  - percolator
  - openms
  - msstitch

- hosts: webserver
  become: true
  tasks:
  - name: Chown all tools to galaxy
    file: path={{ toolshare_dir }} owner=galaxy group=galaxy recurse=yes state=directory
