---
# Installs or updates tools, updates galaxy

- hosts:
  - master
  - workers
  user: admin
  sudo: True
  roles:
  - tool_dependencies
 

- hosts: master
  user: admin
  sudo: True
  vars_files:
  - credentials/user_data.yml
  roles:
  - tools
  - galaxy
