---
# Installs or updates tools, galaxy

# Get hostvars for all boxes
- hosts:
  - workers
  - toolserver
  - mirror
  - ftpserver
  - fileserver
  user: admin
  sudo: true
  tasks:
  - name: Dummy task to get info of boxes
    debug: msg="Connected to box"

- hosts:
  - webserver 
  - workers
  user: admin
  sudo: True
  roles:
  - tool_dependencies

- hosts: toolserver
  user: admin
  sudo: True
  tasks:
  - name: Get github hostkey
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com" 


- hosts: webserver
  user: admin
  sudo: True
  roles:
  - mount_shares
  - proteowizard
  - msgfplus
  - percolator
  - openms
  - proteinquant
  - msstitch
  - hardklor_bullseye
  tasks:
  - name: Fix ownership of all tools
    file: path={{ toolshare_dir }} owner=galaxy group=galaxy recurse=yes state=directory
