---

# Update entire cluster's packages
# For security updates, etc

- hosts: 
  - workers
  sudo: True
  tasks:
  - name: Shutdown SLURM in workers
    service: name=slurm-llnl state=stopped

- hosts: 
  - fileserver
  - mirror
  sudo: True
  tasks:
  - name: Dummy task to get server info
    debug: msg="Connected to fileserver"


- hosts: 
  - fileserver
  - ftpserver
  - webserver 
  - dbserver
  - toolserver
  - workers
  sudo: True
  roles:
  - private_ip
  - update

- hosts: 
  - fileserver
  sudo: True
  roles:
  - reboot

- hosts: 
  - webserver 
  sudo: True
  roles:
  - reboot

- hosts: 
  - ftpserver 
  - workers
  sudo: True
  roles:
  - reboot

- hosts:
  - webserver 
  sudo: True
  roles:
  - slurm
  - nginx

- hosts:
  - workers
  sudo: True
  roles:
  - slurm
