---

# Update entire cluster's packages
# For security updates, etc

- hosts: 
  - workers
  user: admin
  sudo: True
  tasks:
  - name: Shutdown SLURM in workers
    service: name=slurm-llnl state=stopped

- hosts: 
  - fileserver
  - mirror
  user: admin
  sudo: True
  tasks:
  - name: Dummy task to get server info
    debug: msg="Connected to fileserver"

- hosts: 
  - webserver 
  user: admin
  sudo: True
  roles:
  - shutdown_services

- hosts: 
  - fileserver
  - ftpserver
  - webserver 
  - dbserver
  - toolserver
  - workers
  user: admin
  sudo: True
  roles:
  - private_ip
  - update

- hosts: 
  - fileserver
  user: admin
  sudo: True
  roles:
  - reboot

- hosts: 
  - webserver 
  user: admin
  sudo: True
  roles:
  - reboot

- hosts: 
  - ftpserver 
  - workers
  user: admin
  sudo: True
  roles:
  - reboot

- hosts:
  - webserver 
  user: admin
  sudo: True
  roles:
  - slurm
  - nginx

- hosts:
  - workers
  user: admin
  sudo: True
  roles:
  - slurm
