---
# Tasks for installing packages needed on worker and master
# tool dependencies etc. etc.

# Users
- name: Setup galaxy user
  user: name=galaxy comment="Galaxy user" uid=1001 state=present shell=/bin/bash

- name: Install packages required for building
  apt: pkg={{ item }} state=installed
  with_items: build_packages

- name: Install core packages
  apt: pkg={{ item }} state=installed
  with_items: core_packages

- name: Install tool dependencies
  apt: pkg={{ item }} state=installed
  with_flattened: tool_packages

- name: Create mount points
  file: path={{ item }} state=directory
  with_flattened: mount_paths
- name: Mount data volume
  lineinfile: "dest=/etc/fstab 'line={{ data_share_fileserver }}     {{ data_path }}  nfs auto    0   0'"
  when: has_fileserver defined and has_fileserver

# SLURM configuration
- name: Set permissions on /etc
  file: path=/etc state=directory mode=0755
- name: Create munge conf dir
  file: path=/etc/munge state=directory
- name: Put munge key in place 
  copy: src=credentials/{{ mungekey_file }} dest=/etc/munge/munge.key owner=munge mode=0600
- name: Modify hosts file for munge
  lineinfile: "dest=/etc/hosts line='{{ ansible_eth0.ipv4.address }}    {{ ansible_hostname }}'"

- name: Setup slurm user
  user: name=slurm state=present
- name: Setup slurm config dir
  file: path=/etc/slurm-llnl state=directory mode=0755 owner=root group=root
- name: Put slurm config file in place
  template: src=slurm_conf.j2 dest=/etc/slurm-llnl/slurm.conf owner=slurm mode=0755

- name: Install tool python libraries
  pip: name={{ item }} state=present extra_args="--index-url=http://{{master_ip}}/pypimirror/simple"
  with_flattened: tool_python_libraries
  when: use_mirror defined and use_mirror
- name: Install tool python libraries
  pip: name={{ item }} state=present 
  with_flattened: tool_python_libraries
  when: use_mirror not defined or not use_mirror
