---
# Tasks for installing packages needed on most boxes
# tool dependencies etc. etc.


- name: Install locale
  command: /usr/sbin/locale-gen en_US.UTF-8

- name: Set locale
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: Setup galaxy user
  user: name=galaxy comment="Galaxy user" uid=1001 state=present shell=/bin/bash

- name: Fix etc/hosts for gluster
  lineinfile: dest=/etc/hosts
              regexp="^{{ hostvars[item][hostvars[item]['private_ip_port']]['ipv4']['address'] }}"
              line="{{ hostvars[item][hostvars[item]['private_ip_port']]['ipv4']['address'] }}   {{ item }}"
              state=present
  with_items: 
  - "{{ groups['fileserver'] }}"
  - "{{ groups['workers'] }}"
  - "{{ groups['webserver'] }}"
  - "{{ groups['ftpserver'] }}"


