---
# Tasks for installing packages needed on worker and master
# tool dependencies etc. etc.

# Users
- name: Setup galaxy user
  user: name=galaxy comment="Galaxy user" uid=1001 state=present shell=/bin/bash
- name: Setup munge user
  user: name=munge state=present

- name: Install packages required for building
  apt: pkg={{ item }} state=installed
  with_items: build_packages

- name: Install core packages
  apt: pkg={{ item }} state=installed
  with_items: core_packages

- name: Install tool dependencies
  apt: pkg={{ item }} state=installed
  with_flattened: tool_packages

- name: Create mount points
  file: path={{ item }} state=directory
  with_flattened: mount_paths

# SLURM configuration
- name: Set permissions on /etc
  file: path=/etc state=directory mode=0755
- name: Create munge conf dir
  file: path=/etc/munge state=directory
- name: Put munge key in place
  copy: src=mungekey dest=/etc/munge/munge.key owner=munge mode=0600
- name: Modify hosts file for munge
  lineinfile: "dest=/etc/hosts line='{{ ansible_eth0.ipv4.address }}    {{ ansible_hostname }}'"

- name: Setup slurm user
  user: name=slurm state=present
- name: Setup slurm config dir
  file: path=/etc/slurm-llnl state=directory mode=0755 owner=root group=root
- name: Put slurm config file in place
  template: src=slurm_conf.j2 dest=/etc/slurm-llnl/slurm.conf owner=slurm mode=0755

#- name: Allow incoming traffic on port 536 and 537
#  command: iptables -A INPUT -p tcp -i {{ private_interface }} --dport {{ item }} -j ACCEPT
#  with_items:
#    - 536
#    - 537
#- name: Save iptables config
#  command: iptables-save
#- name: Create libc softlink for SGE
#  file: src=/lib/x86_64-linux-gnu/libc-2.15.so dest=/lib64/libc.so.6 state=link
#- name: Remove certain lines in /etc/hosts
#  lineinfile: dest=/etc/hosts regexp="^127.0.1." state=absent
#- name: Add sge_root to /etc/profile
#  lineinfile: dest=/etc/profile insertafter=EOF line="export SGE_ROOT={{ sge_root }}"
#- name: Source SGE settings in /etc/bash.bashrc
#  lineinfile: dest=/etc/bash.bashrc insertafter=EOF line=". $SGE_ROOT/default/common/settings.sh"
 
- name: Fetch XSD for percolator
  get_url: url={{ local_source_mirror }}/{{ xsd_package }} dest=/tmp/{{ xsd_package }}
- name: Install XSD for percolator
  command: dpkg -i {{ xsd_package }} chdir=/tmp

- name: Fetch Xerces for percolator
  get_url: url={{ local_source_mirror }}/{{ xerces_package }} dest=/tmp/{{ xerces_package }}
- name: Untar Xerces source
  command: tar xvfz {{ xerces_package }} chdir=/tmp
- name: Configure Xerces makefile 
  command: ./configure --disable-network --disable-threads chdir=/tmp/{{xerces_directory}}
- name: Make Xerces for percolator
  command: make chdir=/tmp/{{ xerces_directory }}
- name: Install Xerces
  command: make install chdir=/tmp/{{ xerces_directory }}

- name: Install tool python libraries
  pip: name={{ item }} state=present extra_args="--index-url=http://{{master_ip}}/pypimirror/simple"
  with_flattened: tool_python_libraries

- name: Fetch h5py for pycolator
  get_url: url={{ local_source_mirror }}/{{ h5py_package }}.tar.gz dest=/tmp/{{ h5py_package }}.tar.gz
- name: Untar h5py source
  command: tar xvfz {{ h5py_package }}.tar.gz chdir=/tmp
- name: Install h5py
  command: python setup.py install chdir=/tmp/{{ h5py_package }}

