---
# Tasks for installing packages needed on worker and master
# tool dependencies etc. etc.

- name: Install core packages
  apt: name={{ item }} state=installed
  with_items: core_packages

- name: Set locale
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: Setup galaxy user
  user: name=galaxy comment="Galaxy user" uid=1001 state=present shell=/bin/bash

- name: Create mount points
  file: path={{ item }} state=directory
  with_flattened: mount_paths

- name: Mount data, tool, galaxy volumes
  mount: src={{ item.0 }} name={{ item.1 }} fstype=nfs state=mounted 
  with_together:
  - mount_shares
  - mount_paths

- name: Create new bona fide upload_store
  file: path={{ data_path }}/upload_store state=directory
  when: "'master' in group_names"
- name: Start nginx again
  service: name=nginx state=started
  when: "'master' in group_names"
