---
# Admin user should be present, uid 1000, and no other users on the master

# Master preparation tasks to make it a mirror
- name: Setup galaxy user needed for nginx
  user: name=galaxy comment="Galaxy user" uid=1001 state=present shell=/bin/bash
- name: Create galaxy mount point for nginx and other mount points
  file: path={{ item }} state=directory
  with_flattened: mount_paths
  

- name: Install packages for master
  apt: pkg={{ item }} state=installed
  with_items: master_packages
- name: Install packages required for building
  apt: pkg={{ item }} state=installed
  with_items: build_packages # from core vars file

- name: Install virtualenv
  pip: name=virtualenv state=present

# Apt mirror
- name: Creating apt mirror directory
  file: path=/mnt/mirrors/ubuntumirror mode=755 owner=root group=admin state=directory
- name: Setting keyring directory for apt mirror
  file: path=/home/mirrorkeyring state=directory
- name: Importing keyring for apt mirror
  command: gpg --no-default-keyring --keyring /home/mirrorkeyring/trustedkeys.gpg --import /usr/share/keyrings/ubuntu-archive-keyring.gpg
- name: Build apt mirror
  script: mirrorbuild.sh

# Source mirror
- name: Creating source dir for worker downloads
  file: path=/mnt/mirrors/source mode=755 owner=root group=admin state=directory
- name: Downloading source of XSD
  get_url: url={{xsd_location}}/{{xsd_package}} dest=/mnt/mirrors/source/{{ xsd_package }}
- name: Downloading source of Xerces
  get_url: url={{xerces_location}}/{{xerces_package}} dest=/mnt/mirrors/source/{{ xerces_package }}
- name: Downloading source of h5py
  get_url: url={{ h5py_location }}/{{ h5py_package }}.tar.gz dest=/mnt/mirrors/source/{{ h5py_package }}.tar.gz

# PyPI mirror
- name: Install pypi mirror downloader bandersnatch
  pip: name=bandersnatch state=present virtualenv=/home/admin/virtenvs/pypi_mirror
- name: Creating pypi mirror path
  file: path=/mnt/mirrors/pypimirror state=directory
- name: Installing bandersnatch.conf
  copy: src=bandersnatch.conf dest=/etc/bandersnatch.conf  
- name: Build PyPI mirror
  script: pypimirror_builder.sh

# Nginx
- name: Getting nginx source
  command: wget ${nginx_location}/${nginx_package}.tar.gz chdir=/tmp
- name: Untarring source
  command: tar xvfz ${nginx_package}.tar.gz chdir=/tmp
- name: Getting nginx upload module source
  command: wget ${nginx_upl_mod_loc}/${nginx_upl_mod_package}.tar.gz chdir=/tmp
- name: Untarring source
  command: tar xvfpz ${nginx_upl_mod_package}.tar.gz chdir=/tmp
- name: Configuring makefile for nginx
  command: chdir=/tmp/${nginx_package} ./configure --prefix=/opt/nginx --with-ipv6 --add-module=../${nginx_upl_mod_package} --user=galaxy --group=galaxy --with-http_ssl_module --with-http_gzip_static_module --with-cc-opt=-Wno-error --with-debug
- name: Making nginx from source
  command: make chdir=/tmp/${nginx_package}
- name: Install nginx
  command: make install chdir=/tmp/${nginx_package}
- name: Stow nginx
  command: stow nginx chdir=/opt
- name: Adding nginx configuration file
  copy: src=nginx.conf dest=/opt/nginx/conf/nginx.conf
- name: Softlinking nginx executable
  file: src=/opt/nginx/sbin/nginx dest=/usr/sbin/nginx state=link
- name: Create init script for nginx
  copy: src=nginx_init dest=/etc/init.d/nginx mode=755
- name: Add nginx to default run levels
  service: name=nginx enabled=yes


# Install ansible
- name: Install ansible on master for worker installations
  pip: name=ansible state=present virtualenv=/home/admin/virtenvs/ansible
- name: Get latest stable ansible scripts from github
  git: repo=git://github.com/glormph/proteomics_configuration
       dest=/home/admin/proteomics_configuration
- name: Move hosts file to repo on host
  copy: src=inventory/hosts
        dest=/home/admin/proteomics_configuration/adapt_cluster_provisioning/inventory/hosts
- name: Move clusterdata to repo on host
  copy: src=inventory/cluster_data.yml
        dest=/home/admin/proteomics_configuration/adapt_cluster_provisioning/inventory/cluster_data.yml

# Prepare munge key
- name: Create mungekey
  shell: dd if=/dev/urandom bs=1 count=1024 >/home/admin/mungekey

- name: Make new admin homedir contents owned by admin user
  file: path=/home/admin/virtenvs state=directory owner=admin group=admin recurse=yes
  file: path=/home/admin/proteomics_configuration state=directory owner=admin group=admin recurse=yes
